### PR TITLE
Fix focused option if `defaultMenuIsOpen` is set

### LINKED ISSUE #4013: 3.1.0: Selected value not focused/visible when using defaultMenuIsOpen or menuIsOpen
Example: https://codesandbox.io/s/zealous-leaf-58ett?file=/src/index.js

@Tirzono Here you go, thanks for looking at this

### PR DESCRIPTION
**Pull request by Rall3n**
Fix #4013

This PR fixes the behaviour around `defaultMenuIsOpen` so that the selected option is visible on mount.

### CODE REVIEW

File: packages/react-select/src/Select.tsx [hunk 1]
```diff
@@ -623,6 +623,13 @@ export default class Select<
     this.instancePrefix =
       'react-select-' + (this.props.instanceId || ++instanceId);
     this.state.selectValue = cleanValue(props.value);
+
+    // Set focusedOption if menuIsOpen is set on init (e.g. defaultMenuIsOpen)
+    if (props.menuIsOpen && this.state.selectValue.length) {
+      const focusableOptions = this.buildFocusableOptions();
+      const optionIndex = focusableOptions.indexOf(this.state.selectValue[0]);
```
Comment (Rall3n) [inline packages/react-select/src/Select.tsx:630]: Object equality should not be a problem at this point as this happens before mount.
But could still be changed to compare values instead.

**Review by lukebennett88 — APPROVED** [review]
